#!/bin/sh
BOOTCONF="/boot/batocera-boot.conf"

. /etc/profile.d/xdg.sh
. /etc/profile.d/dbus.sh

case "$1" in
  start)
    emulationstation-standalone &
  ;;

  stop)
    emulationstation-standalone --stop-rebooting
    killall retroarch openbox sway touchegg 2>/dev/null
    if killall emulationstation 2>/dev/null
    then
      sleep 20 &
      watchdog=$!
      while [ -n "$(pidof emulationstation)" ]; do
        sleep 0.25
        kill -0 $watchdog || exit
      done
      kill -9 $watchdog
    fi
  ;;

  restart|reload)
    "$0" stop
    "$0" start
  ;;

  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
  ;;
esac

exit $?
