#!/bin/sh

case "$1" in
  start)
    # Look for a swap partition
    SWAPFILE=$(blkid -c /dev/null -l -o device -t TYPE=swap)
    # Look for CHOKO_DISK partition and create a swapfile there
    if [ -z "$SWAPFILE" ] && [ "$(grep -c /media/CHOKO_DISK /proc/mounts)" -gt 0 ]
    then
      SWAPFILE=/media/CHOKO_DISK/swapfile
      if [ ! -f "$SWAPFILE" ]
      then
        fallocate -l 512M $SWAPFILE
        chmod 600 $SWAPFILE
        mkswap $SWAPFILE
      fi
    fi
    # Check if we are in SD card and create a swapfile there
    if [ -z "$SWAPFILE" ] && [ "$(batocera-part share_internal)" = "/dev/mmcblk0p3" ]
    then
      SWAPFILE=/userdata/system/swapfile
      if [ ! -f "$SWAPFILE" ]
      then
        fallocate -l 512M $SWAPFILE
        chmod 600 $SWAPFILE
        mkswap $SWAPFILE
      fi
    fi
    [ -n "$SWAPFILE" ] && swapon -f "$SWAPFILE"
    # Avoid user browsing other partitions on CHA with RetroArch
    [ -e /media/CHA_BOOT ] && umount /media/CHA_BOOT && rmdir /media/CHA_BOOT
    [ -e /media/CHA_BOOT_SD ] && umount /media/CHA_BOOT_SD && rmdir /media/CHA_BOOT_SD
    [ -e /media/CHA_DISK ] && umount /media/CHA_DISK && rmdir /media/CHA_DISK
    [ -e /media/CHA_DISK_SD ] && umount /media/CHA_DISK_SD && rmdir /media/CHA_DISK_SD
    [ -e /media/BATOCERA_DISK ] && umount /media/BATOCERA_DISK && rmdir /media/BATOCERA_DISK
    [ -e /media/BATOCERA_DISK_SD ] && umount /media/BATOCERA_DISK_SD && rmdir /media/BATOCERA_DISK_SD
    [ -e /media/CHA ] && umount /media/CHA && rmdir /media/CHA
    [ $(grep -c '/dev/mmcblk1p2 /media/NO_LABEL' /proc/mounts) -gt 0 ] && umount /media/NO_LABEL && rmdir /media/NO_LABEL
    ;;
  stop)
    swapoff -a
    ;;
  restart|reload)
    "$0" stop
    "$0" start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac
